project:
  type: website
  output_dir:docs
website:
  title: "Matthew S. Channing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



