---
title: "CV"
format: html
---

## Education

Doctorate Degree

Planning and Public Affairs

University of Oregon

2024-Present \| GPA 3.88

Graduate Degree

Public Administration

San Francisco State University

2013-2015 \| GPA 3.87

Undergraduate Degree 

Political Science

UC Santa Barbara

2008 - 2011 \| GPA 3.37

## Work Experience

+--------------------------------------------------------------------------------------------------------------------------------------------------+
| **Research Assistant, 2024-Present**                                                                                                             |
|                                                                                                                                                  |
| University of Oregon, Eugene, OR                                                                                                                 |
|                                                                                                                                                  |
| -   Conduct literature review                                                                                                                    |
|                                                                                                                                                  |
| -   Interview research subjects                                                                                                                  |
|                                                                                                                                                  |
| -   Manage data for thematic coding                                                                                                              |
|                                                                                                                                                  |
| -   Co-design survey research instruments                                                                                                        |
|                                                                                                                                                  |
| **PPPM Student Teacher, 2024-Present**                                                                                                           |
|                                                                                                                                                  |
| University of Oregon, Eugene, OR                                                                                                                 |
|                                                                                                                                                  |
| -   Quantitative Research Methods, F24, S25, F25                                                                                                 |
|                                                                                                                                                  |
| -   Intro to Public Policy, W25                                                                                                                  |
|                                                                                                                                                  |
| -   Intro to City Planning S26, F26                                                                                                              |
|                                                                                                                                                  |
| -   Intro to Healthy Communities W27                                                                                                             |
|                                                                                                                                                  |
| -   Guest Lecture: Intro to Public Policy, Inclusive Urbanism, Intro to City Planning                                                            |
|                                                                                                                                                  |
| **Agricultural Preservation Specialist, 2020 - 2024**                                                                                            |
|                                                                                                                                                  |
| County of Kent, Grand Rapids, MI                                                                                                                 |
|                                                                                                                                                  |
| -   Reviewed township zoning ordinances and maps for compatibility with County land use goals and program fit                                    |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Presented program information, population data, and land use considerations to elected officials, appointed boards, and public townhalls     |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Supported County officials in strategizing collaborative regional planning for density and open space                                        |
|                                                                                                                                                  |
| **Assistant Management Analyst, 2017 - 2019**                                                                                                    |
|                                                                                                                                                  |
| City of Berkeley, Berkeley, CA                                                                                                                   |
|                                                                                                                                                  |
| -   Determined address service area using mapping software                                                                                       |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Managed grants investing in the urban tree canopy                                                                                            |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Reviewed parks ordinances with concerned public and elected officials for food production and temporary shelters caused by housing shortages |
+--------------------------------------------------------------------------------------------------------------------------------------------------+
